---
# This file is managed via modulesync
# https://github.com/voxpupuli/modulesync
# https://github.com/theforeman/foreman-installer-modulesync
HOSTS:
  ubuntu-1404-x64.example.com:
    platform: ubuntu-14.04-amd64
    hypervisor: docker
    image: ubuntu:14.04
    docker_preserve_image: true
    docker_cmd: '["/sbin/init"]'
    docker_image_commands:
      - 'rm /usr/sbin/policy-rc.d'
      - 'rm /sbin/initctl; dpkg-divert --rename --remove /sbin/initctl'
      - 'apt-get install -y net-tools wget'
      - 'locale-gen en_US.UTF-8'
CONFIG:
  trace_limit: 200
  masterless: true
...
# vim: syntax=yaml
