fixtures:
  repositories:
    apache:           'git://github.com/puppetlabs/puppetlabs-apache'
    concat:           'git://github.com/puppetlabs/puppetlabs-concat'
    concat_native:    'git://github.com/theforeman/puppet-concat'
    mysql:            'git://github.com/puppetlabs/puppetlabs-mysql'
    postgresql:       'git://github.com/puppetlabs/puppetlabs-postgresql'
    puppet:           'git://github.com/theforeman/puppet-puppet'
    stdlib:           'git://github.com/puppetlabs/puppetlabs-stdlib'
    tftp:             'git://github.com/theforeman/puppet-tftp'


  symlinks:
    foreman: "#{source_dir}"
