fixtures:
  repositories:
    apache:           'git://github.com/puppetlabs/puppetlabs-apache'
    apt:              'git://github.com/puppetlabs/puppetlabs-apt'
    concat:           'git://github.com/puppetlabs/puppetlabs-concat'
    extlib:           'git://github.com/voxpupuli/puppet-extlib'
    mysql:            'git://github.com/puppetlabs/puppetlabs-mysql'
    postgresql:       'git://github.com/puppetlabs/puppetlabs-postgresql'
    puppet:           'git://github.com/theforeman/puppet-puppet'
    stdlib:           'git://github.com/puppetlabs/puppetlabs-stdlib'


  symlinks:
    foreman: "#{source_dir}"
