fixtures:
  repositories:
    apache:           'http://github.com/puppetlabs/puppetlabs-apache'
    apt:              'http://github.com/puppetlabs/puppetlabs-apt'
    concat:           'http://github.com/puppetlabs/puppetlabs-concat'
    extlib:           'http://github.com/voxpupuli/puppet-extlib'
    mysql:            'http://github.com/puppetlabs/puppetlabs-mysql'
    postgresql:       'http://github.com/puppetlabs/puppetlabs-postgresql'
    puppet:           'http://github.com/theforeman/puppet-puppet'
    stdlib:           'http://github.com/puppetlabs/puppetlabs-stdlib'
