fixtures:
  repositories:
    alternatives:     'git://github.com/adrienthebo/puppet-alternatives'
    apache:           'git://github.com/puppetlabs/puppetlabs-apache'
    apt:
      repo:           'git://github.com/puppetlabs/puppetlabs-apt'
      branch:         '1.8.x'
    concat:           'git://github.com/puppetlabs/puppetlabs-concat'
    mysql:            'git://github.com/puppetlabs/puppetlabs-mysql'
    postgresql:       'git://github.com/puppetlabs/puppetlabs-postgresql'
    puppet:           'git://github.com/theforeman/puppet-puppet'
    stdlib:
      repo:           'git://github.com/puppetlabs/puppetlabs-stdlib'
      branch:         '4.7.x'
    tftp:             'git://github.com/theforeman/puppet-tftp'

  symlinks:
    foreman: "#{source_dir}"
