fixtures:
  repositories:
    apache: 'https://github.com/puppetlabs/puppetlabs-apache'
    apt: 'https://github.com/puppetlabs/puppetlabs-apt'
    augeas_core: 'https://github.com/puppetlabs/puppetlabs-augeas_core'
    certs: 'https://github.com/theforeman/puppet-certs'
    concat: 'https://github.com/puppetlabs/puppetlabs-concat'
    cron_core: 'https://github.com/puppetlabs/puppetlabs-cron_core'
    extlib: 'https://github.com/voxpupuli/puppet-extlib'
    hashfile: 'https://github.com/southalc/hashfile'
    iop_advisor_engine: 'https://github.com/theforeman/puppet-iop_advisor_engine'
    podman: 'https://github.com/southalc/podman'
    postgresql: 'https://github.com/puppetlabs/puppetlabs-postgresql'
    puppet: 'https://github.com/theforeman/puppet-puppet'
    redis: 'https://github.com/voxpupuli/puppet-redis'
    systemd: 'https://github.com/voxpupuli/puppet-systemd'
    selinux_core: 'https://github.com/puppetlabs/puppetlabs-selinux_core'
    stdlib: 'https://github.com/puppetlabs/puppetlabs-stdlib'
    yumrepo_core: 'https://github.com/puppetlabs/puppetlabs-yumrepo_core'
