fixtures:
  repositories:
    apache:           'git://github.com/puppetlabs/puppetlabs-apache'
    concat:
      repo:           'git://github.com/ripienaar/puppet-concat'
      ref:            '04356974f72b90a1d0f57346a00e95a717924e43'
    concat_native:    'git://github.com/theforeman/puppet-concat'
    mysql:
      repo:           'git://github.com/puppetlabs/puppetlabs-mysql'
      ref:            '52fb70ebdeb74f66bedc54196c0884c2b84699f3'
    postgresql:       'git://github.com/puppetlabs/puppetlabs-postgresql'
    puppet:           'git://github.com/theforeman/puppet-puppet'
    stdlib:           'git://github.com/puppetlabs/puppetlabs-stdlib'


  symlinks:
    foreman: "#{source_dir}"
