---
Gemfile:
  extra:
    - gem: json
    - gem: webmock
spec/spec_helper.rb:
  requires:
    - webmock/rspec
    - puppet/reports
  extra_code: |
    def static_fixture_path
      File.join(File.dirname(__FILE__), 'static_fixtures')
    end
