---
.travis.yml:
  beaker_sets:
    - centos7-64
    - debian10-64
    - ubuntu1804-64
  env:
    global:
      - PARALLEL_TEST_PROCESSORS=8
Gemfile:
  extra:
    - gem: webmock
      version: '~> 2.0'
    - gem: oauth
spec/spec_helper.rb:
  requires:
    - webmock/rspec
    - puppet/reports
