---
.travis.yml:
  beaker_sets:
    - docker/centos-7
    - docker/debian-8
  env:
    global:
      - PARALLEL_TEST_PROCESSORS=16
Gemfile:
  extra:
    - gem: webmock
      version: '~> 2.0'
    - gem: oauth
Rakefile:
  param_docs_pattern:
    - manifests/cli.pp
    - manifests/cli/*.pp
    - manifests/init.pp
    - manifests/compute/*.pp
    - manifests/plugin/*.pp
spec/spec_helper.rb:
  requires:
    - webmock/rspec
    - puppet/reports
  extra_code: |
    def static_fixture_path
      File.join(File.dirname(__FILE__), 'static_fixtures')
    end

    Dir["./spec/support/**/*.rb"].sort.each { |f| require f }
