---
Gemfile:
  extra:
    - gem: json
    - gem: webmock
    - gem: addressable
      version: '< 2.4'
      options:
        platforms:
        - 'ruby_18'
Rakefile:
  param_docs_pattern:
    - manifests/cli.pp
    - manifests/init.pp
    - manifests/compute/*.pp
    - manifests/plugin/*.pp
spec/spec_helper.rb:
  requires:
    - webmock/rspec
    - puppet/reports
  extra_code: |
    def static_fixture_path
      File.join(File.dirname(__FILE__), 'static_fixtures')
    end
