---
.travis.yml:
  beaker_sets:
    - centos7-64
    - debian9-64
  env:
    global:
      - PARALLEL_TEST_PROCESSORS=8
Gemfile:
  extra:
    - gem: webmock
      version: '~> 2.0'
    - gem: oauth
Rakefile:
  param_docs_pattern:
    - manifests/cli.pp
    - manifests/cli/*.pp
    - manifests/init.pp
    - manifests/compute/*.pp
    - manifests/plugin/*.pp
spec/spec_helper.rb:
  requires:
    - webmock/rspec
    - puppet/reports
