---
.travis.yml:
  beaker_sets:
    - docker/centos-7
    - docker/debian-8
Gemfile:
  extra:
    - gem: webmock
      version: '< 2.0'
    - gem: addressable
      version: '< 2.4'
      options:
        platforms:
        - 'ruby_18'
    - gem: oauth
Rakefile:
  param_docs_pattern:
    - manifests/cli.pp
    - manifests/cli/*.pp
    - manifests/init.pp
    - manifests/compute/*.pp
    - manifests/plugin/*.pp
spec/spec_helper.rb:
  requires:
    - webmock/rspec
    - puppet/reports
  extra_code: |
    def static_fixture_path
      File.join(File.dirname(__FILE__), 'static_fixtures')
    end

    Dir["./spec/support/**/*.rb"].sort.each { |f| require f }
spec/spec_helper_acceptance.rb:
  modules:
    - puppet-extlib
    - puppetlabs-apt
