name    'theforeman-foreman'
version '1.3.0'
source 'git://github.com/theforeman/puppet-foreman'
author 'theforeman'
license 'GPLv3+'
summary 'Foreman server configuration'
description 'Module for configuring Foreman'
project_page 'http://github.com/theforeman/foreman-installer'

dependency 'theforeman/apache', '>= 1.3.0'
dependency 'theforeman/concat_native', '>= 1.3.0'
dependency 'theforeman/passenger', '>= 1.3.0'

dependency 'puppetlabs/postgresql', '>= 2.2.0'
dependency 'puppetlabs/stdlib'
