name    'theforeman-foreman'
version '0.0.1'
source 'https://github.com/theforeman/puppet-foreman.git'
author 'theforeman'
#license 'TODO'
summary 'Puppet module for Foreman'
description 'Puppet module for Foreman'
project_page 'https://github.com/theforeman/puppet-foreman'

#dependency 'camptocamp/apt', '>=0.0.2'
#dependency 'theforeman/passenger', 'TODO'
#dependency 'theforeman/apache', 'TODO'
