name: Acceptance tests

on: pull_request

jobs:
  build_cache:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: "2.7"
      - uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-2.7-gems-acceptance-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-2.7-gems-acceptance-
      - name: Install dependencies
        run: |
          gem install bundler
          bundle config path vendor/bundle
          bundle config without 'development test'
          bundle install --jobs 4 --retry 3
  acceptance:
    needs: build_cache
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        setfile:
          - centos7-64{hostname=centos7-64.example.com}
          - centos8-64{hostname=centos8-64.example.com}
          - debian10-64{hostname=debian10-64.example.com}
          - ubuntu1804-64{hostname=ubuntu1804-64.example.com}
        puppet:
          - "6"
          - "5"
    name: Puppet ${{ matrix.puppet }} - ${{ matrix.setfile }}
    steps:
      - name: Enable IPv6 on docker
        run: |
          echo '{"ipv6":true,"fixed-cidr-v6":"2001:db8:1::/64"}' | sudo tee /etc/docker/daemon.json
          sudo service docker restart
      - uses: actions/checkout@v2
      - name: Setup ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: "2.7"
      - uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-2.7-gems-acceptance-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-2.7-gems-acceptance-
      - name: Install dependencies
        run: |
          gem install bundler
          bundle config path vendor/bundle
          bundle config without 'development test'
          bundle install --jobs 4 --retry 3
      - name: Run tests
        run: bundle exec rake beaker
        env:
          BEAKER_PUPPET_COLLECTION: puppet${{ matrix.puppet }}
          BEAKER_setfile: ${{ matrix.setfile }}
